remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
minimal_mistakes_skin: "dark"
title: "hexhub"
author: "Nikhil Harry (@nikhilhex)"
description: "the best blog in the history of blogs"
issues_repo: nikhilhex/blog-comments
google_analytics: G-KGH9JWLR21
